services:
  bot:
    image: ${IMAGE_REF}
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - TZ=UTC
    # If the image is in a private GHCR, make sure you've run:
    #   echo <PAT> | docker login ghcr.io -u <github-username> --password-stdin
