name: docker-multiarch

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "V*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute tags
        id: vars
        shell: bash
        run: |
          REPO_LC="${GITHUB_REPOSITORY,,}"
          GHCR_IMAGE="ghcr.io/${REPO_LC}"
          SHA_TAG="sha-${GITHUB_SHA::7}"
          TAGS="${GHCR_IMAGE}:latest,${GHCR_IMAGE}:${SHA_TAG}"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            REF="${GITHUB_REF_NAME}"
            TAGS="$TAGS,${GHCR_IMAGE}:${REF}"
          fi
          echo "repo_lc=${REPO_LC}" >> "$GITHUB_OUTPUT"
          echo "ghcr_image=${GHCR_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub (optional)
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.vars.outputs.tags }}

      - name: Build and push (Docker Hub)
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('docker.io/{0}/{1}:{2}', secrets.DOCKERHUB_USERNAME, github.event.repository.name, github.ref_name) || '' }}
